name: Test

on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: yarn install
      - run: yarn prettier:lint

  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: yarn install
      - run: yarn eslint:printRules
      - run: |
          if [ "$(git status --porcelain)" != "" ]; then
            echo "Some rules have changed"
            exit 1
          else
            echo "No changes detected in snapshots"
          fi
