name: Test

on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: yarn install
      - run: yarn prettier:lint

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: yarn install
      - run: yarn eslint:lint

  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: yarn install
      - run: TEST_CONFIG=angular TEST_FILE=index.ts yarn eslint:printRules
      - run: TEST_CONFIG=angular TEST_FILE=index.spec.ts yarn eslint:printRules
      - run: TEST_CONFIG=angular TEST_FILE=index.model.spec.ts yarn eslint:printRules
      - run: TEST_CONFIG=angular TEST_FILE=index.model.ts yarn eslint:printRules
      - run: TEST_CONFIG=angular TEST_FILE=index.abstract.ts yarn eslint:printRules
      - run: TEST_CONFIG=angular TEST_FILE=index.html yarn eslint:printRules

  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: yarn install
      - run: TEST_CONFIG=react-ts TEST_FILE=index.ts yarn eslint:printRules
      - run: TEST_CONFIG=react-ts TEST_FILE=src/Mocks/Data/index.ts yarn eslint:printRules
      - run: TEST_CONFIG=react-ts TEST_FILE=index.spec.ts yarn eslint:printRules
      - run: TEST_CONFIG=react-ts TEST_FILE=src/Generated/index.ts yarn eslint:printRules
     
